### ISSUE TITLE
Make error on Big Sur 11.2.3

### ISSUE THREAD

**Issue by ancientjpeg** [soerenbnoergaard/reverse-camel#1]
Attempting to make on macOS Big Sur gives the following error:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src/reverse-camel/
Makefile:21: ../../dpf/Makefile.plugins.mk: No such file or directory
make[1]: *** No rule to make target `../../dpf/Makefile.plugins.mk'.  Stop.
make: *** [all] Error 2
```

Currently using GNU Make 3.81. I have also noticed the dpf folder is empty when this repo is cloned. Forgive anything I've overlooked, I'm brand new to make!

**Comment by soerenbnoergaard** [comment]
If the dpf folder is empty, you have to update the git submodules before typing make - you can see the procedure here: 

https://github.com/soerenbnoergaard/talchorus

Let me know if this works for you!

Thanks,
Søren

**Comment by ancientjpeg** [comment]
Thanks so much !!! Sorry you had to teach a newbie about git today :) the make succeeds and the plugin works great in Ableton Live 11 on my machine. Thank you!
