### ISSUE TITLE
make error arch linux

### ISSUE THREAD

**Issue by ryottmp3** [soerenbnoergaard/reverse-camel#2]
make -C src/reverse-camel/
make[1]: Entering directory '/home/ryott/Build/reverse-camel-0.0.4/src/reverse-camel'
Makefile:21: ../../dpf/Makefile.plugins.mk: No such file or directory
make[1]: *** No rule to make target '../../dpf/Makefile.plugins.mk'.  Stop.
make[1]: Leaving directory '/home/ryott/Build/reverse-camel-0.0.4/src/reverse-camel'
make: *** [Makefile:4: all] Error 2

**Comment by soerenbnoergaard** [comment]
Did you clone the submodules after cloning the repo?

    git submodule update --init

Best regards,
Søren

**Comment by ryottmp3** [comment]
just saw this. ill try when I get home. thanks!

**Comment by ryottmp3** [comment]
Okay, It seems to have fixed the issue thank you.
